### ISSUE TITLE
Output not achieved

### ISSUE THREAD

**Issue by vim5818** [lucasw/rviz_textured_quads#14]
![issue](https://user-images.githubusercontent.com/53337387/80734279-377e0f00-8b0f-11ea-8de4-f03c5581b051.png)
I get such an output after running your demo.launch.

I would like some support to achieve the desired results for this repository.

**Comment by lucasw** [comment]
Are you feeding an rviz_camera_stream into the textured quad?  What did you expect to see?

**Comment by vim5818** [comment]
Thank you for the response. 
I would like to use your textured quads for projecting a "recorded video" or a sequence of images(in 2D) which I will play from my rosbag (as image topic ) in a 3D space.

I followed the procedure:
1. I cloned your  (https://github.com/lucasw/rviz_camera_stream), ran it's demo. I saw the RViz of your camera Stream open and that's all. Not sure what to be expected as output.
2. Then I cloned and ran your Rviz_textured_quads demo.

Finally, I was able to see the 2 Rviz windows as indicated in the screenshot of my previous comment.
Unfortunately, I could not understand what is the relation between the 2 Rviz and how they are connected. I could not get any visualisation as shown in the readme file of rviz quads textured.

Can you please provide with some sort of detailed steps to achieve my requirement using your repo as I am beginner in ROS.
Thank you.

**Comment by lucasw** [comment]
The rviz_camera_stream is just there to provide a changing image topic - a simpler demo would be to to use image_publisher.

If you have the demo running and your rosbag playing you should be able to open the MeshCustomDisplay properties and select your desired image topic:

![rviz_textured_quads_image_topic](https://user-images.githubusercontent.com/1334122/80819188-5a4d0980-8b89-11ea-98c9-b10b6546f65d.png)

It should then appear attached to the `quad` tf frame.  You can select another frame with the 'Quad Frame' drop down, `map` is a good default choice because it doesn't depend on any other tf frames existing.

The `CameraPub` rviz plugin instance can be removed.  You don't really need anything else in the demo.launch file, in your own rviz window you can add a `MeshDisplayCustom` and set the topic and frame and see the image.
